import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import React from "react";

import FrontPage from "@/components/FrontPage";

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  return (
    <div
      className="fullPage"
      style={{
        backgroundImage:
          'url("https://cdn.wallpapersafari.com/30/44/PDXw7N.jpg")',
        height: "100vh",
        backgroundRepeat: "no-repeat",
        backgroundSize: "cover",
      }}
    >
      <Head>
        <title>Trip planner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FrontPage />
      <marquee className="marquee" direction="right">
        Check out the details here !!!
      </marquee>
    </div>
  );
}
